/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/0000-0000 HOUSE ASSEMBLY-REV B_bundled.glb --transform 
Files: public/models/0000-0000 HOUSE ASSEMBLY-REV B_bundled.glb [55.72MB] > /home/wavefire/sync/code/utsbi-web/0000-0000 HOUSE ASSEMBLY-REV B_bundled-transformed.glb [2.89MB] (95%)
*/

import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/0000-0000 HOUSE ASSEMBLY-REV B_bundled-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera makeDefault={false} far={100} near={0.01} fov={49.996} position={[35.85, 56.633, 95.632]} rotation={[-0.422, -0.708, -0.284]} />
      <PerspectiveCamera makeDefault={false} far={100} near={0.01} fov={49.996} position={[245.292, 79.982, 194.287]} rotation={[-0.233, 0.564, 0.126]} />
      <PerspectiveCamera makeDefault={false} far={100} near={0.01} fov={49.996} position={[225.095, 84.115, 1.407]} rotation={[-2.683, 0.627, 2.86]} />
      <PerspectiveCamera makeDefault={false} far={100} near={0.01} fov={49.996} position={[271.882, 112.065, 270.346]} rotation={[-0.968, -0.311, -0.419]} />
      <PerspectiveCamera makeDefault={false} far={100} near={0.01} fov={49.996} position={[434.819, 61.22, 198.335]} rotation={[-2.481, -0.573, -2.743]} />
      <PerspectiveCamera makeDefault={false} far={100} near={0.01} fov={49.996} position={[-95.135, 51.408, -4.607]} rotation={[-2.128, 0.808, 2.282]} />
      <PerspectiveCamera makeDefault={false} far={100} near={0.01} fov={49.996} position={[-278.414, 52.21, -302.624]} rotation={[-2.683, 0.553, 2.888]} />
      <PerspectiveCamera makeDefault={false} far={100} near={0.01} fov={49.996} position={[377.468, 118.268, -577.248]} rotation={[-2.877, 0.641, 2.981]} />
      <PerspectiveCamera makeDefault={false} far={100} near={0.01} fov={49.996} position={[-287.36, 114.005, 588.66]} rotation={[-0.24, -0.677, -0.152]} />
      <PerspectiveCamera makeDefault={false} far={100} near={0.01} fov={49.996} position={[-877.708, 232.435, 1237.128]} rotation={[-0.104, -0.589, -0.058]} />
      <PerspectiveCamera makeDefault={false} far={100} near={0.01} fov={49.996} position={[90.405, 99.161, 1553.348]} rotation={[-0.112, 0.148, 0.017]} />
      <PerspectiveCamera makeDefault={false} far={100} near={0.01} fov={49.996} position={[23.006, 73.675, 140.019]} rotation={[-2.036, 0.696, 2.235]} />
      <mesh geometry={nodes['0000-0000_HOUSE_ASSEMBLY0000-0001_FOUNDATION'].geometry} material={materials.CONCRETE} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/0000-0000 HOUSE ASSEMBLY-REV B_bundled-transformed.glb')
